In [ ]:
!sudo add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!sudo apt-get update -qq 2>&1 > /dev/null
!sudo apt -y install -qq google-drive-ocamlfuse 2>&1 > /dev/null
!google-drive-ocamlfuse

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Connection failed [IP: 185.125.190.39 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.


debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 851: /usr/bin/x

In [ ]:
!sudo apt-get install -qq w3m # to act as web browser 
!xdg-settings set default-web-browser w3m.desktop # to set default browser
%cd /content
!mkdir drive
%cd drive
!mkdir MyDrive
%cd ..
%cd ..
!google-drive-ocamlfuse /content/drive/MyDrive

debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package w3m.
(Reading database ... 124021 files and directories currently installed.)
Preparing to unpack .../w3m_0.5.3-36ubuntu0.1_amd64.deb ...
Unpacking w3m (0.5.3-36ubuntu0.1) ...
Setting up w3m (0.5.3-36ubuntu0.1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
/content
/content/drive
/content
/
Access token retrieved correctly.


In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

ValueError: ignored

In [ ]:
# %pip install mediapipe
%pip install autokeras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.4/162.4 KB 17.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.7/135.7 KB 20.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 76.5 MB/s eta 0:00:00


In [ ]:
%ls

drive/  sample_data/


In [ ]:
%pip install onnxruntime-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 MB 14.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 KB 6.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 KB 11.5 MB/s eta 0:00:00


In [ ]:
import cv2
import mediapipe as mp
import json
import numpy as np
import onnxruntime
import time
import numpy as np

mp_face_detection = mp.solutions.face_detection
model = "emotion-ferplus-8.onnx"
session = onnxruntime.InferenceSession(model, providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'])
input_name = session.get_inputs()[0].name
output_name = session.get_outputs()[0].name 

In [ ]:
%pip install deeplake

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 414.2/414.2 KB 10.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.7/132.7 KB 4.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.8/79.8 KB 2.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 78.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 95.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.6/79.6 KB 4.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 KB 4.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.0/132.0 KB 16.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 KB 18.3 MB/s eta 0:00:00
  Created wheel for deeplake: filename=deeplake-3.1.9-py3-none-any.whl size=505166 sha256=b2e615c4c2e0121a78b6e1ab6728f086df261e53709979

In [ ]:
import deeplake
ds_train = deeplake.load('hub://activeloop/fer2013-train')
ds_test = deeplake.load('hub://activeloop/fer2013-public-test')

hub://activeloop/fer2013-train loaded successfully.
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/activeloop/fer2013-train
hub://activeloop/fer2013-public-test loaded successfully.
This dataset can be visualized in Jupyter Notebook by ds.visualize() or at https://app.activeloop.ai/activeloop/fer2013-public-test


In [ ]:
train_ds

<BatchDataset element_spec=(TensorSpec(shape=(None, 48, 48, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [ ]:
test_ds

<DatasetAdapter element_spec={'images': TensorSpec(shape=(48, 48), dtype=tf.uint8, name=None), 'labels': TensorSpec(shape=(1,), dtype=tf.uint32, name=None)}>

In [ ]:
ds_train.images[0]

Tensor(key='images', index=Index([0]))

In [ ]:
train_ds1 = ds_train.tensorflow()
test_ds1 = ds_test.tensorflow()

In [ ]:
train_ds1.take(32)

<DatasetAdapter element_spec={'images': TensorSpec(shape=(48, 48), dtype=tf.uint8, name=None), 'labels': TensorSpec(shape=(1,), dtype=tf.uint32, name=None)}>

In [ ]:
tr = tuple(zip(*train_ds1))

In [ ]:
images, labels = tr

In [ ]:
images

('images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',
 'images',

In [ ]:
import tensorflow as tf

In [ ]:
# %cd content/drive/MyDrive/AffectNet
%cd content/drive/MyDrive/fer2013
# %cd MyDrive/
%ls

/content/drive/MyDrive/fer2013
emotion-ferplus-8.onnx  knn.joblib     test/      train/
image_classifier/       svmfer.joblib  test_csv/  train_csv/


In [ ]:
import tensorflow as tf
train_ds = tf.keras.utils.image_dataset_from_directory(
  "train/",
  # validation_split=0.2,
  seed=123,
  image_size=(48, 48),
  batch_size=32)

Found 28709 files belonging to 7 classes.


In [ ]:
train_ds.class_names

['angry', 'disgust', 'fear', 'happy', 'neutral', 'sad', 'surprise']

In [ ]:
test_ds = tf.keras.utils.image_dataset_from_directory(
  "test/",
  # validation_split=0.2,
  seed=123,
  image_size=(48, 48),
  batch_size=32)

test_ds.class_names

Found 7178 files belonging to 7 classes.


['angry', 'disgust', 'fear', 'happy', 'neutral', 'sad', 'surprise']

In [ ]:
for _, label in train_ds.take(1):
  print(label)

tf.Tensor([2 5 5 4 0 5 5 0 3 2 6 5 6 0 3 3 1 0 2 6 5 0 3 4 0 2 6 5 2 4 6 5], shape=(32,), dtype=int32)


In [ ]:
import autokeras as ak

with tf.device('/device:GPU:0'):
  clf = ak.ImageClassifier(max_trials=1)
  # Feed the tensorflow Dataset to the classifier.
  clf.fit(train_ds, epochs=100)
# Predict with the best model.
predicted_y = clf.predict(test_ds)
# Evaluate the best model with testing data.
print(clf.evaluate(test_ds))

model = clf.export_model()

print(type(model))  # <class 'tensorflow.python.keras.engine.training.Model'>

try:
    model.save("model_autokeras", save_format="tf")
except Exception:
    model.save("model_autokeras.h5")

TypeError: ignored

In [ ]:
train = {}
test = {}
for label in os.listdir("train"):
  if os.path.isdir(os.path.join("test", label)):
    train[label] = os.listdir("train/" + label)

for label in os.listdir("test"):
  if os.path.isdir(os.path.join("test", label)):
    test[label] = os.listdir("test/" + label)

# print(train["angry"][:2])
print(test["sad"][:2])

['PublicTest_28215339.jpg', 'PublicTest_24936833.jpg']


In [ ]:
emotion_to_label = {'neutral':0, 'happy':1, 'surprise':2, 'sad':3, 
                     'anger':4, 'disgust':5, 'fear':6, 'contempt':7}

In [ ]:
import pandas as pd

df = pd.read_csv('labels.csv')
df.loc[0]['pth']
# df.loc[0, 'label']

'anger/image0000006.jpg'

In [ ]:
import cv2
import mediapipe as mp
import numpy as np
import time
import os

In [ ]:
LANDMARK_IDS = np.array((61, 292, 0, 17, 50, 280, 48, 4, 289, 206, 426, 133, 130, 159, 
                145, 362, 359, 386, 374, 122, 351, 46, 105, 107, 276, 334, 336))

EDGE_IDS = ((0, 2), (0, 3), (1, 2), (1, 3), (7, 6), (7, 8), (6, 4), (8, 5),
            (6, 9), (9, 0), (4, 0), (8, 10), (10, 1), (7, 19), (7, 20), (7, 0),
            (7, 1), (19, 23), (19, 14), (23, 22), (22, 21), (21, 12), (12, 13),
            (12, 14), (11, 13), (11, 14), (14, 4), (20, 26), (26, 25), (25, 24),
            (24, 16), (16, 17), (16, 18), (15, 17), (15, 18), (18, 20), (18, 5))

ANGLE_IDS = ((2, 0, 3), (0, 2, 1), (6, 7, 8), (9, 7, 10), (0, 7, 1), (1, 5, 8),
             (1, 10, 8), (13, 12, 14), (21, 22, 23), (6, 19, 23))

FEATURE_IDS = [LANDMARK_IDS[np.array(triplet)] for triplet in ANGLE_IDS]
FEATURE_IDS

[array([ 0, 61, 17]),
 array([ 61,   0, 292]),
 array([ 48,   4, 289]),
 array([206,   4, 426]),
 array([ 61,   4, 292]),
 array([292, 280, 289]),
 array([292, 426, 289]),
 array([159, 130, 145]),
 array([ 46, 105, 107]),
 array([ 48, 122, 107])]

In [ ]:
mp_face_mesh = mp.solutions.face_mesh

In [ ]:
def unit_vector(vector):
    """ Returns the unit vector of the vector.  """
    return vector / np.linalg.norm(vector)

def angle_between(landmarks):
    l1, l2, l3 = landmarks
    v1 = l1 - l2
    v2 = l3 - l2
    v1_u = unit_vector(v1)
    v2_u = unit_vector(v2)
    return np.degrees(np.arccos(np.clip(np.dot(v1_u, v2_u), -1.0, 1.0)))

def extract_features(landmarks, triplet_ids):
  triplet = landmarks[triplet_ids]
  return {
      "landmarks" : triplet,
      "angle" : angle_between(triplet)
  }

def extract_angles_only(landmarks, triplet_ids):
  triplet = landmarks[triplet_ids]
  return angle_between(triplet)

In [ ]:
def get_face_mesh(image_data):
  image_file = image_data
  # label = image_data[1]
  with mp_face_mesh.FaceMesh(
    static_image_mode=True,
    max_num_faces=1,
    refine_landmarks=True,
    min_detection_confidence=0.5) as face_mesh:
    
    image = cv2.imread(image_file)
    # Convert the BGR image to RGB before processing.
    results = face_mesh.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

    # Print and draw face mesh landmarks on the image.
    if not results.multi_face_landmarks:
      return
    normalized_landmarks = results.multi_face_landmarks[0].landmark
    face_landmarks = np.array([(normalized_landmarks[idx].x, normalized_landmarks[idx].y) for idx in LANDMARK_IDS])
    # face_landmarks = np.array([(landmark.x, landmark.y) for landmark in normalized_landmarks])
    angles = np.array([extract_angles_only(face_landmarks, np.array(triplet)) for triplet in ANGLE_IDS])
    # angles = np.array([triplet['angle'] for triplet in triplets])
    return angles
    # return {
    #     'landmarks' : face_landmarks,
    #     # 'triplets' : triplets,
    #     'angles' : angles,
    #     'label' : emotion_to_label[label]
    # }

In [ ]:
start = time.time()
# vcl = get_face_mesh(df.loc[3])
vcl = get_face_mesh("train/disgust/" + train['disgust'][0])
end = time.time()
print(end - start)
print(vcl)
# vcl1 = get_face_mesh(df.loc[3]['pth'])[1]
# vcl2 = get_face_mesh(df.loc[3]['pth'])[2]
# vv = vcl, vcl1, vcl2

0.82586669921875
[ 47.57842264 144.28863911 162.13046292 104.64804901  39.14565965
  52.58216292 107.47972605  44.24531531  99.51712304 152.78718726]


In [ ]:
print(vcl['landmarks'][0:4])
# print(vcl['triplets'][:2])
print(vcl['angles'][:2])
print(vcl['label'])

[[0.38099712 0.78048635]
 [0.65095383 0.77458584]
 [0.53179842 0.71523124]
 [0.52632064 0.85515076]]
[ 50.59244057 130.12161748]
6


In [ ]:
df['pth']

0           anger/image0000006.jpg
1           anger/image0000007.jpg
2           anger/image0000012.jpg
3           anger/image0000035.jpg
4           anger/image0000060.jpg
                   ...            
30997    surprise/image0034961.jpg
30998    surprise/image0034966.jpg
30999    surprise/image0034973.jpg
31000    surprise/image0034977.jpg
31001    surprise/image0042075.jpg
Name: pth, Length: 31002, dtype: object

In [ ]:
def log_steps(row, i):
  if (i%10==0):
    print(i)
  return classify_emotion(row)
  # if d == None:
  #   return None
  # return np.append(d['angles'], d['label'])

In [ ]:
dat = zip(df['pth'], df['label'])

In [ ]:
def softmax(x):
    x = x.reshape(-1)
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

def postprocess(scores):
    prob = softmax(scores)
    prob = np.squeeze(prob)
    classes = np.argsort(prob)[::-1]
    return classes

def detect_face(image_file: str):
  with mp_face_detection.FaceDetection(
    model_selection=1, min_detection_confidence=0.5) as face_detection:
  
    image = cv2.imread(image_file)
      # Convert the BGR image to RGB and process it with MediaPipe Face Detection.
    results = face_detection.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    if not results.detections:
      return "not result"

  return results

def get_face_from_detection(img, results):
  x_min = abs(results.detections[0].location_data.relative_bounding_box.xmin)
  y_min = abs(results.detections[0].location_data.relative_bounding_box.ymin)
  width = abs(results.detections[0].location_data.relative_bounding_box.width)
  height = abs(results.detections[0].location_data.relative_bounding_box.height)

  h, w, c = img.shape 
  face = img[round(h*y_min) : round(h*(y_min + height)), 
             round(w*x_min) : round(w*(x_min + width))]
  face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)
  face = cv2.resize(face, dsize=(64,64), interpolation=cv2.INTER_CUBIC)
  face_data = np.resize(face, (1, 1, 64, 64))
  return face_data

    
def run(input_data):
    try:
        # load in our data, convert to readable format
        data = np.array(input_data).astype('float32')
        
        start = time.time()
        r = session.run([output_name], {input_name : data})
        end = time.time()
        
        # result = emotion_map(postprocess(r[0]))
        
        result_dict = {"result": postprocess(r[0]),
                      "time_in_sec": [end - start]}
    except Exception as e:
        result_dict = {"error": str(e)}
    return result_dict
    # return json.dumps(result_dict)

def classify_emotion(file_name):
    results = detect_face(file_name)
    if type(results) == str:
      return None
    image = cv2.imread(file_name)
    face = get_face_from_detection(image, results)
    emotion = run(face)
    return emotion

In [ ]:
test_emo = {}
for label in ("neutral", "happy", "surprise", "sad", "angry", "disgust", "fear"):
  print(label)
  temp = [log_steps("test/" + label + "/" + filename, i) for i, filename in enumerate(test[label])]
  test_emo[label] = [i for i in temp if i is not None]

neutral
0
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
1000
1010
1020
1030
1040
1050
1060
1070
1080
1090
1100
1110
1120
1130
1140
1150
1160
1170
1180
1190
1200
1210
1220
1230
happy
0
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
1000
1010
1020
1030
1040
1050
1060
1070
1080
1090
1100
1110
1120
1130
1140
1150
1160
117

In [ ]:
test_emo['happy']

[{'result': array([1, 0, 7, 2, 3, 4, 5, 6]),
  'time_in_sec': [0.001245260238647461]},
 {'result': array([1, 2, 0, 4, 3, 7, 6, 5]),
  'time_in_sec': [0.0011982917785644531]},
 {'result': array([1, 0, 2, 3, 4, 7, 5, 6]),
  'time_in_sec': [0.0011889934539794922]},
 {'result': array([1, 0, 2, 3, 7, 4, 6, 5]),
  'time_in_sec': [0.0026962757110595703]},
 {'result': array([1, 0, 7, 2, 3, 4, 5, 6]),
  'time_in_sec': [0.001222848892211914]},
 {'result': array([1, 0, 2, 7, 3, 4, 5, 6]),
  'time_in_sec': [0.0013985633850097656]},
 {'result': array([1, 0, 2, 7, 3, 6, 4, 5]),
  'time_in_sec': [0.0012154579162597656]},
 {'result': array([1, 0, 2, 7, 3, 4, 6, 5]),
  'time_in_sec': [0.0019297599792480469]},
 {'result': array([1, 0, 7, 2, 3, 5, 4, 6]),
  'time_in_sec': [0.0011763572692871094]},
 {'result': array([1, 0, 3, 4, 7, 2, 5, 6]),
  'time_in_sec': [0.0020151138305664062]},
 {'result': array([0, 3, 4, 7, 5, 2, 1, 6]),
  'time_in_sec': [0.0012431144714355469]},
 {'result': array([1, 0, 2, 4, 3, 

In [ ]:
test_labels = []
test_all = []

for i, label in enumerate(("neutral", "happy", "surprise", "sad", "angry", "disgust", "fear")):
  test_labels += len(test_emo[label]) * [i]
  test_all += [sample['result'][0] for sample in test_emo[label]]

In [ ]:
len(test['happy'])

1774

In [ ]:
import pandas as pd
train_angles = {}
test_angles = {}
for label in ("neutral", "angry", "fear", "disgust", "surprise", "sad", "happy"):
  print(label)
  temp = [log_steps("train/" + label + "/" + filename, i) for i, filename in enumerate(train[label])]
  train_angles[label] = [i for i in temp if i is not None]
  lgpd = pd.DataFrame(train_angles[label])
  lgpd.to_csv("train/"+label+".csv", index=False)

print("TEST")

for label in ("neutral", "angry", "fear", "disgust", "surprise", "sad", "happy"):
  print(label)
  temp = [log_steps("test/" + label + "/" + filename, i) for i, filename in enumerate(test[label])]
  test_angles[label] = [i for i in temp if i is not None]
  lgpd = pd.DataFrame(test_angles[label])
  lgpd.to_csv("test/"+label+".csv", index=False)

neutral
0
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
1000
1010
1020
1030
1040
1050
1060
1070
1080
1090
1100
1110
1120
1130
1140
1150
1160
1170
1180
1190
1200
1210
1220
1230
1240
1250
1260
1270
1280
1290
1300
1310
1320
1330
1340
1350
1360
1370
1380
1390
1400
1410
1420
1430
1440
1450
1460
1470
1480
1490
1500
1510
1520
1530
1540
1550
1560
1570
1580
1590
1600
1610
1620
1630
1640
1650
1660
1670
1680
1690
1700
1710
1720
1730
1740
1750
1760
1770
1780
1790
1800
1810
1820
1830
1840
1850
1860
1870
1880
1890
1900
1910
1920
1930
1940
1950
1960
1970
1980
1990
2000
2010
2020
2030
2040
2050
2060
2070
2080
2090
2100
2110
2120
2130
2140
2150
2160
2170
2180
2190
220

In [ ]:
len(train_angles["angry"])

3555

In [ ]:
train_labels = []
train_all = []
test_labels = []
test_all = []

for i, label in enumerate(("neutral", "angry", "fear", "disgust", "surprise", "sad", "happy")):
  train_labels += len(train_angles[label]) * [i]
  train_all += train_angles[label]
  test_labels += len(test_angles[label]) * [i]
  test_all += test_angles[label]

print(len(test_labels), len(train_all))
print(train_labels[5], train_labels[8556])

6678 26705
0 2


In [ ]:
test_labels[-3000]

4

In [ ]:
# ret = df.apply(lambda image_data : get_face_mesh(image_data), axis=1)
ret = [log_steps(row, i) for i, row in enumerate(dat)]
ret = [i for i in ret if i is not None]
ret_pd = pd.DataFrame(ret)
ret_pd.to_csv("out.csv", index=False)

0
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
1000
1010
1020
1030
1040
1050
1060
1070
1080
1090
1100
1110
1120
1130
1140
1150
1160
1170
1180
1190
1200
1210
1220
1230
1240
1250
1260
1270
1280
1290
1300
1310
1320
1330
1340
1350
1360
1370
1380
1390
1400
1410
1420
1430
1440
1450
1460
1470
1480
1490
1500
1510
1520
1530
1540
1550
1560
1570
1580
1590
1600
1610
1620
1630
1640
1650
1660
1670
1680
1690
1700
1710
1720
1730
1740
1750
1760
1770
1780
1790
1800
1810
1820
1830
1840
1850
1860
1870
1880
1890
1900
1910
1920
1930
1940
1950
1960
1970
1980
1990
2000
2010
2020
2030
2040
2050
2060
2070
2080
2090
2100
2110
2120
2130
2140
2150
2160
2170
2180
2190
2200
2210
2

In [ ]:
labels = ret_pd[10].to_numpy().astype(int)
labels[:10]

array([2, 4, 4, 6, 4, 4, 5, 4, 4, 4])

In [ ]:
ret_dp = ret_pd.drop(columns=[10])
ret_dp

In [ ]:
train_data = ret_dp.values.tolist()
train_data[:3]

[[57.23937923406727,
  135.1352082534739,
  152.65382214081876,
  138.23265669565765,
  71.35675144715965,
  38.53920608389093,
  92.44720273548559,
  39.49847327861469,
  117.98501646856471,
  140.2725944137026],
 [16.76060692989818,
  176.3864741609542,
  178.5006230822628,
  165.34564163996896,
  86.00611818581716,
  31.904227016323908,
  81.66324379818819,
  15.675502552805662,
  137.61969620472632,
  136.33865294198918],
 [63.274786552325295,
  127.33736037702923,
  144.38152165204514,
  134.79879651203055,
  84.36679142988905,
  43.113254667300154,
  95.7647785613774,
  25.159696581168063,
  129.8905187103011,
  135.6894425634344]]

In [ ]:
%pip install joblib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from joblib import dump, load
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.utils import shuffle
from sklearn.svm import SVC

# train = train_data[:30000]
# train_labels = labels[:30000]

# test = train_data[30000:]
# test_labels = labels[30000:]

train_shuffled, labels_shuffled = shuffle(train_all, train_labels)
test_shuffled, test_labels_shuffled = shuffle(test_all, test_labels)

# neigh = KNeighborsClassifier(n_neighbors=1)
# neigh.fit(train_shuffled, labels_shuffled)

clf = make_pipeline(StandardScaler(), SVC(C=275, gamma='scale', kernel='rbf'))
clf.fit(train_shuffled, labels_shuffled)

# dump(neigh, 'knn.joblib') 
dump(clf, 'svmfer.joblib')

['svmfer.joblib']

In [ ]:
dump(clf, 'svm.joblib')

['svm.joblib']

In [ ]:
scores

array([0.37233333, 0.394     , 0.37733333, 0.37966667, 0.387     ,
       0.397     , 0.37833333, 0.371     , 0.36766667, 0.38533333])

In [ ]:
cross_val_predict(neigh, train, train_labels, cv=10)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(test_labels, test_all)

0.6104252400548696

In [ ]:
from sklearn.metrics import accuracy_score

start = time.time()
# predicted = neigh.predict(test_shuffled)
predicted = clf.predict(test_shuffled)
acc = accuracy_score(test_labels_shuffled, predicted)
end = time.time()
print("time", end - start)
print("acc", acc)

time 8.7755606174469
acc 0.5163222521713088


In [ ]:
ret_pd = pd.DataFrame(ret)

In [ ]:
ret_pd.to_csv("out.csv", index=False)

In [ ]:
print(vv)
print(angle_between(vv))

(array([0.38099712, 0.78048635]), array([0.65095383, 0.77458584]), array([0.53179842, 0.71523124]))
27.73129177037118
